package bi.gov.obr.informationServices.enums;


public enum UserAction {

    ADD_POSTE_COLLECTE,
    UPDATE_POSTE_COLLECTE,
    DELETE_POSTE_COLLECTE,
    ADD_EXERCICE,
    UPDATE_EXERCICE,
    DELETE_EXERCICE,

    ADD_COMPTE_IMPOT,
    UPDATE_COMPTE_IMPOT,
    DELETE_COMPTE_IMPOT,
    ADD_SOUS_COMPTE_IMPOT,
    UPDATE_SOUS_COMPTE_IMPOT,
    DELETE_SOUS_COMPTE_IMPOT,



}
